// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdTzt6TXgeHiBD-HVNjN1PSwAw50jwGHg',
    appId: '1:117776492273:web:d06076be715665eada2b50',
    messagingSenderId: '117776492273',
    projectId: 'mangga-origin',
    authDomain: 'mangga-origin.firebaseapp.com',
    storageBucket: 'mangga-origin.appspot.com',
    measurementId: 'G-5J6VDKZEGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpuxxqFQrsMohkLMa30tJAsc_59sQP-dg',
    appId: '1:117776492273:android:5a774ee920a20026da2b50',
    messagingSenderId: '117776492273',
    projectId: 'mangga-origin',
    storageBucket: 'mangga-origin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9ZtlhkBvJdW3MZfgF6Dshaa6t1SkEyb0',
    appId: '1:117776492273:ios:288ee4863cec8fc0da2b50',
    messagingSenderId: '117776492273',
    projectId: 'mangga-origin',
    storageBucket: 'mangga-origin.appspot.com',
    androidClientId: '117776492273-g7r66qdij6uv2lcn60e9tis5ndvvm9t6.apps.googleusercontent.com',
    iosClientId: '117776492273-n36e9e89tq0dejopban4tm3qg9dhorhl.apps.googleusercontent.com',
    iosBundleId: 'com.luru.mangga',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9ZtlhkBvJdW3MZfgF6Dshaa6t1SkEyb0',
    appId: '1:117776492273:ios:288ee4863cec8fc0da2b50',
    messagingSenderId: '117776492273',
    projectId: 'mangga-origin',
    storageBucket: 'mangga-origin.appspot.com',
    androidClientId: '117776492273-g7r66qdij6uv2lcn60e9tis5ndvvm9t6.apps.googleusercontent.com',
    iosClientId: '117776492273-n36e9e89tq0dejopban4tm3qg9dhorhl.apps.googleusercontent.com',
    iosBundleId: 'com.luru.mangga',
  );
}
