// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnhCezjEPjS6fd2aA7T6bV-nHFC7G7dRE',
    appId: '1:1020165745334:web:93269b54a28e90bd4fd417',
    messagingSenderId: '1020165745334',
    projectId: 'luru-90257',
    authDomain: 'luru-90257.firebaseapp.com',
    storageBucket: 'luru-90257.appspot.com',
    measurementId: 'G-5LC0X24C3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdX9qUYEYSAm7Kd3UFIQpkDSPv_Hu8gn4',
    appId: '1:1020165745334:android:e81fd204e01e18674fd417',
    messagingSenderId: '1020165745334',
    projectId: 'luru-90257',
    storageBucket: 'luru-90257.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMvOeljLDEodNlT8SoaF1EhRnNpIlkgdA',
    appId: '1:1020165745334:ios:a1545cca4e0375314fd417',
    messagingSenderId: '1020165745334',
    projectId: 'luru-90257',
    storageBucket: 'luru-90257.appspot.com',
    androidClientId:
        '1020165745334-k5d204haojb0qu8d7nmqehev9krmmrid.apps.googleusercontent.com',
    iosClientId:
        '1020165745334-js9uurmgbt0oqnmdkqsuf4u69qesrieg.apps.googleusercontent.com',
    iosBundleId: 'com.luru.muria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMvOeljLDEodNlT8SoaF1EhRnNpIlkgdA',
    appId: '1:1020165745334:ios:a1545cca4e0375314fd417',
    messagingSenderId: '1020165745334',
    projectId: 'luru-90257',
    storageBucket: 'luru-90257.appspot.com',
    androidClientId:
        '1020165745334-k5d204haojb0qu8d7nmqehev9krmmrid.apps.googleusercontent.com',
    iosClientId:
        '1020165745334-js9uurmgbt0oqnmdkqsuf4u69qesrieg.apps.googleusercontent.com',
    iosBundleId: 'com.luru.muria',
  );
}
